from snakemake.utils import min_version

##### set minimum snakemake version #####
#min_version("6.4.1")


##### setup report #####
#configfile: "config/config.yaml"


report: "report/workflow.rst"



##### load rules #####

include: "rules/sealevel.smk"
include: "rules/common.smk"
include: "rules/climate.smk"
include: "rules/topography.smk"
include: "rules/heatflux.smk"
include: "rules/sediment.smk"


##### pism experiments ####
include: "rules/experiment_files.smk"

##### data sets
include: "rules/present_day_greenland.smk"


include: "rules/pism_exps.smk"
include: "rules/exp_gi.smk"

# postprocessing
include: "rules/postprocessing.smk"

##### target rules #####

# rule all:
#     input:
#         get_final_output(),
#         "results/qc/multiqc_report.html",
#         "results/pca.svg",
