
use_spack: True
header_local: "mpirun -np 4 ~/pism-sbeyer/bin/pismr \\"

times:
  ts_times: 10
  ex_times: 100



PISM_grids: 
    GRN_20km: "-Mx  76 -My 141 -Mz 101 -Mbz 11 -Lz 4000 -Lbz 2000"
    NHEM_20km: "-Mx 625 -My 625 -Mz 101 -Mbz 11 -Lz 5000 -Lbz 2000"
    


PISM_always_on: 
  - "-options_left True"
  - "-tauc_slippery_grounding_lines True"
  - "-timestep_hit_multiples 1"
  - "-backup_interval 5"
  - "-stress_balance.sia.max_diffusivity 100000"
  - "-geometry.ice_free_thickness_standard 10"
  - "-grid.registration corner"
  - "-z_spacing equal"
  - "-energy.enthalpy.temperate_ice_thermal_conductivity_ratio 0.01"
  - "-energy.basal_melt.use_grounded_cell_fraction False"
  
PISM_marine_ice_sheets:
  - "-cfbc True"
  - "-kill_icebergs True"
  - "-part_grid True"
  - "-subgl"

PISM_extra_vars: "-extra_vars topg,thk,mask,velsurf_mag,velsurf,velbase_mag,tillwat,tauc,temppabase,climatic_mass_balance,effective_precipitation,effective_air_temp"

default_resources_large:
    nodes: 8
    partition: standard96
    time: "12:00:00"

header_local: "mpirun -np 4 ~/pism-sbeyer/bin/pismr \\"
